### PR TITLE
Move shared client sources to clients/common

### PR DESCRIPTION
**Pull request by cgmb**
This change moves all the headers and sources that are common to the test and benchmark clients into `clients/common/test`, `clients/common/containers` or `clients/common/misc`.

### CODE REVIEW

**Review by jzuniga-amd — COMMENTED** [review]
This looks good. I'm OK with the changes. What do you think @tfalders?

**Comment by tfalders** [comment]
Hmmmm... the test code feels too deeply nested now. Perhaps the auxiliary, lapack, and refact folders should go directly into common rather than common/test.

**Comment by cgmb** [comment]
Done. That left testing_managed_malloc.hpp in an odd position, so I moved it directly into clients/gtest as it is only used in rocsolver-test.

**Comment by jzuniga-amd** [comment]
I'll merge this now. Thanks Cory.

**Pull request merged**
